#version 430

layout(binding = 0, r16i) uniform iimageBuffer voxels;
layout(binding = 1, r32ui) uniform uimageBuffer voxels_col;

uniform int WIDTH;
uniform int HEIGHT;
uniform int DEPTH;

layout(local_size_x = 1, local_size_y = 1) in;
void main() {
  ivec3 vcoords = ivec3(gl_GlobalInvocationID.xyz);
  int index = vcoords.z * WIDTH * HEIGHT + vcoords.y * WIDTH + vcoords.x;
  int density = (vcoords.x < WIDTH / 2 && vcoords.y < HEIGHT / 2 && vcoords.z < DEPTH / 2) ? 50 : 0; 
  unsigned int color = 0xff00f0ff;

  imageStore(voxels, index, ivec4(density, 0, 0, 0));
  imageStore(voxels_col, index, ivec4(color, 0, 0, 0));
}